# Generated by Django 5.1.3 on 2025-01-04 15:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_api', '0001_initial'),
    ]

    operations = [
        # Step 1: Remove the existing ManyToManyField
        migrations.RemoveField(
            model_name='order',
            name='medicines',
        ),
        # Step 2: Recreate the ManyToManyField with the desired properties
        migrations.AddField(
            model_name='order',
            name='medicines',
            field=models.ManyToManyField(
                related_name='ordered_medicines',
                to='pharmacy_api.OrderedMedicine',
            ),
        ),
    ]
