# Generated by Django 5.1.3 on 2025-01-03 18:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_api', '0002_alter_medicine_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='order',
            name='medicines',
            field=models.ManyToManyField(through='pharmacy_api.OrderedMedicine', to='pharmacy_api.medicine'),
        ),
        migrations.CreateModel(
            name='OrderedPrescriptionImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='prescriptions_images/')),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_api.order')),
            ],
        ),
        migrations.AddField(
            model_name='order',
            name='prescription_images',
            field=models.ManyToManyField(blank=True, related_name='ordered_prescription_images', to='pharmacy_api.orderedprescriptionimage'),
        ),
        migrations.DeleteModel(
            name='PrescriptionImage',
        ),
    ]
