# Generated by Django 5.1.4 on 2025-01-05 22:20

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_api', '0002_alter_order_medicines'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='cart',
            name='status',
        ),
        migrations.CreateModel(
            name='CartMedicine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField()),
                ('cart', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_api.cart')),
                ('medicine', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='pharmacy_api.medicine')),
            ],
        ),
        migrations.AddField(
            model_name='cart',
            name='medicines',
            field=models.ManyToManyField(related_name='cart_medicines', to='pharmacy_api.cartmedicine'),
        ),
    ]
