# Generated by Django 5.1.4 on 2025-01-05 22:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_api', '0003_remove_cart_created_at_remove_cart_order_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cart',
            name='medicines',
            field=models.ManyToManyField(blank=True, related_name='cart_medicines', to='pharmacy_api.cartmedicine'),
        ),
    ]
