# Generated by Django 5.1.4 on 2025-01-06 17:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('pharmacy_api', '0006_alter_order_status'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='payment',
            name='order',
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_method',
            field=models.CharField(choices=[('ondelivery', 'On Delivery'), ('card', 'Card')], default='ondelivery', max_length=255),
        ),
    ]
